---
services:
  html2md-flask:
    image: steffsson/html2md-flask:latest
    container_name: html2md-flask
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-change-me-in-production-use-openssl-rand-hex-32}
    volumes:
      - ./logs:/app/logs
    networks:
      - frontend
    expose:
      - "5000"
    restart: unless-stopped

networks:
  frontend:
    external: true