---
services:
  html2md-flask:
    build: .
    image: ghcr.io/steff-sson/html2md-flask:latest
    container_name: html2md-flask
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - FLASK_ENV=production
    volumes:
      - ./logs:/app/logs
    networks:
      - frontend
    ports:
      - "5000:5000"
    restart: unless-stopped

networks:
  frontend:
    external: true